FROM python:3.13-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir cryptography

COPY backend/ .

RUN chmod +x scripts/entrypoint.sh

EXPOSE 8010
ENTRYPOINT ["bash", "scripts/entrypoint.sh"]
